### ISSUE TITLE
Live example doesn't show records for memories

### ISSUE THREAD

**Issue by giadasp** [joaqcid/my-memories#2]
Thank you for your lovely tutorial, 
Before trying to perform all the tasks I wanted to take a look at the live version of your code at the link you wrote at the end of the tutorial. I added a memory and saved! it but in the page "View My Memories" nothing appears...
Is that normal?

**Comment by joaqcid** [comment]
Hi Giada!

I've set rules to not allow read or writes, that's why you are not seeing
any changes.

Try creating a firebase project, replace config with your project's and try
again.

Remember to set rules enable all access, so you can actually save / read
from firebase

{
  "rules": {
    ".read": true,
    ".write": true
  }
}



joaq

**Comment by giadasp** [comment]
Thank you very much!
I'm not at that step of the tutorial yet. I think there is no issue though.
I will close my issue.

**Comment by giadasp** [comment]
So I've done everything the tutorial explained but I've the following problems:
- my app doesn't route in the right way, if I click "add-memory" or "view-memories" nothing happens, the url changes but the page do not. I need to reload the page to see the right page.
- I still cannot see the data in view-memories. I set all the rules correctly, infact I have the saved data in my database (only in local) but the app is not able to output them in the table. In the deployed app I cannot even daved the data in the database, everything I save is displayed in the log but not stored in the database.

**Comment by joaqcid** [comment]
hmm, that's weird, i'll need to look at your code, to understand why is not working.

**Comment by giadasp** [comment]
I first tried to follow all the steps and it didn't work so I just copied
the github folder and changed firebase config and still not working.

Il mar 30 ott 2018, 14:07 Joaquin Cid <notifications@github.com> ha scritto:

**Comment by joaqcid** [comment]
did you run npm install? are you getting any errors?

**Comment by giadasp** [comment]
No. I'm not getting any error.
I don't k ow if angular 7 can creates some problem since your tutorial is
for angular 6.

Il mar 30 ott 2018, 14:23 Joaquin Cid <notifications@github.com> ha scritto:

**Comment by joaqcid** [comment]
you need to run npm install to get all dependendecies, and then ng serve
